export interface OrderModel{
    "order-api": boolean,
    "order_bill": number,
    "order_chatbot": boolean,
    "order_create_time": string,
    "order_discount": number,
    "order_discount_code": string,
    "order_end_date": string,
    "order_id": number,
    "order_link": boolean,
    "order_month_duration": number,
    "order_online_support": boolean,
    "order_payment_status": string,
    "order_permanent_store": boolean,
    "order_project_id": number,
    "order_ref_id": number,
    "order_renewal": boolean,
    "order_sentiment_service": boolean,
    "order_start_date": string,
    "order_summary_service": boolean,
    "order_tax": number,
    "order_ticketing_system": boolean,
    "order_total_bill": number,
    "order_voice_service": boolean,
    "order_website": boolean,
    "project_logo": string,
    "project_name": string,
}